name: Create Keystore

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Create Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore BoyosHisab.keystore \
            -alias boyoshisab \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass BoyosHisab@2026 \
            -keypass BoyosHisab@2026 \
            -dname "CN=Boyos Hisab, OU=App, O=Boyos Hisab, L=Guwahati, ST=Assam, C=IN"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: BoyosHisab-Keystore
          path: BoyosHisab.keystore
